apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: electrolyzer
      defaultBucket: electrolyzer_data
      tlsSkipVerify: true
    secureJsonData:
      token: influx-token-2024
    editable: true